import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/navigation/Header";
import Providers from "@/src/store/Providers";
import ToastNotification from "@/components/ui/ToastNotification";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Macropay CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        <Providers>
          {children}
        </Providers>

        <ToastNotification />
      </body>
    </html>
  );
}
